# Generated by Django 3.1.6 on 2021-03-31 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0003_auto_20210331_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='remote_sender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
