# Generated by Django 3.1.6 on 2021-04-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0004_friendrequest_remote_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='remote_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
