# Generated by Django 3.1.6 on 2021-04-11 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0031_auto_20210410_2154'),
        ('Search', '0005_friendrequest_remote_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Profile.author'),
        ),
    ]
