# Generated by Django 3.1.6 on 2021-03-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description2',
        ),
    ]
