# Generated by Django 3.2 on 2021-04-09 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='friend_requests_cleared',
            field=models.ManyToManyField(related_name='friend_requests_cleared', to='Search.FriendRequest'),
        ),
        migrations.AddField(
            model_name='author',
            name='posts_cleared',
            field=models.ManyToManyField(related_name='posts_cleared', to='Profile.Post'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
