
# Generated by Django 3.1.6 on 2021-03-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20210305_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('text/markdown', 'Markdown'), ('text/plain', 'Plain'), ('application/base64', 'Base64'), ('image/png', 'Png'), ('image/jpeg', 'Jpeg')], default='text/plain', max_length=40),
        ),
    ]
