# Generated by Django 3.1.6 on 2021-03-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20210303_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
