# Generated by Django 3.1.7 on 2021-03-24 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20210315_1714'),
        ('Profile', '0003_auto_20210316_1556'),
    ]

    operations = [
    ]
