# Generated by Django 3.1.6 on 2021-03-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20210324_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='who_liked',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='who_liked',
        ),
    ]
