# Generated by Django 3.1.6 on 2021-03-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20210227_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followers',
            new_name='following',
        ),
    ]
