# Generated by Django 3.1.6 on 2021-03-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_auto_20210324_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.post'),
        ),
    ]
