# Generated by Django 3.1.7 on 2021-03-24 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_auto_20210324_0041'),
        ('Profile', '0004_merge_20210323_2300'),
    ]

    operations = [
    ]
