# Generated by Django 3.1.6 on 2021-03-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_commentlike_post_id'),
        ('Profile', '0006_auto_20210324_0041'),
    ]

    operations = [
    ]
