# Generated by Django 3.1.6 on 2021-03-24 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_merge_20210324_1528'),
        ('Profile', '0004_merge_20210323_1530'),
        ('Profile', '0008_merge_20210324_1348'),
    ]

    operations = [
    ]
