# Generated by Django 3.1.6 on 2021-03-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_remove_author_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='posts_cleared',
            field=models.ManyToManyField(related_name='posts_cleared', to='Profile.Post'),
        ),
    ]
