# Generated by Django 3.1.6 on 2021-03-31 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_author_posts_cleared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
