# Generated by Django 3.1.6 on 2021-03-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0013_remove_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='displayName',
            field=models.CharField(blank=True, default='<django.db.models.fields.related.OneToOneField>', max_length=50),
        ),
    ]
