# Generated by Django 3.1.6 on 2021-03-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0018_author_remote_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='remote_host',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
