# Generated by Django 3.1.6 on 2021-03-31 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0020_auto_20210331_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='remote_followers_uuid',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AddField(
            model_name='author',
            name='remote_following_uuid',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AddField(
            model_name='author',
            name='remote_friends_uuid',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
