# Generated by Django 3.1.6 on 2021-04-01 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0021_auto_20210331_1545'),
        ('Profile', '0021_auto_20210331_1743'),
    ]

    operations = [
    ]
