# Generated by Django 3.2 on 2021-04-10 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0027_auto_20210407_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='friends',
        ),
    ]
