# Generated by Django 3.2 on 2021-04-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0005_friendrequest_remote_username'),
        ('Profile', '0029_auto_20210410_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='follow_items',
        ),
        migrations.AddField(
            model_name='inbox',
            name='follow_items',
            field=models.ManyToManyField(null=True, related_name='inbox_follows', to='Search.FriendRequest'),
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='follow_items_cleared',
        ),
        migrations.AddField(
            model_name='inbox',
            name='follow_items_cleared',
            field=models.ManyToManyField(null=True, related_name='inbox_follows_cleared', to='Search.FriendRequest'),
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='post_items',
        ),
        migrations.AddField(
            model_name='inbox',
            name='post_items',
            field=models.ManyToManyField(null=True, related_name='inbox_posts', to='Profile.Post'),
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='post_items_cleared',
        ),
        migrations.AddField(
            model_name='inbox',
            name='post_items_cleared',
            field=models.ManyToManyField(null=True, related_name='inbox_posts_cleared', to='Profile.Post'),
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='post_like_items',
        ),
        migrations.AddField(
            model_name='inbox',
            name='post_like_items',
            field=models.ManyToManyField(null=True, related_name='inbox_likes', to='Profile.PostLike'),
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='post_like_items_cleared',
        ),
        migrations.AddField(
            model_name='inbox',
            name='post_like_items_cleared',
            field=models.ManyToManyField(null=True, related_name='inbox_likes_cleared', to='Profile.PostLike'),
        ),
    ]
