# Generated by Django 3.2 on 2021-04-11 03:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0030_auto_20210410_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='friend_requests_cleared',
        ),
        migrations.RemoveField(
            model_name='author',
            name='posts_cleared',
        ),
    ]
