# Generated by Django 3.1.6 on 2021-04-12 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0031_auto_20210410_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='remote_friends_uuid',
        ),
    ]
