# Generated by Django 3.2 on 2021-04-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0032_remove_author_remote_friends_uuid'),
    ]

    operations = [
    ]
