# Generated by Django 3.1.6 on 2021-04-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0037_author_remote_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
    ]
