# Generated by Django 3.1.6 on 2021-04-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0038_author_is_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='debug',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
