# Generated by Django 3.1.6 on 2021-04-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0041_auto_20210414_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_json',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='author_json',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='author_json',
            new_name='author',
        ),
    ]
