# Generated by Django 3.2 on 2021-04-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
