# Generated by Django 3.1.6 on 2021-03-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
