# Generated by Django 3.1.6 on 2021-04-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210409_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='incoming_password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
